### PR TITLE
User download

### PR DESCRIPTION
**Pull request by jlegind**
user_download module for multiple species keys download. Can also takes a polygon as a parameter.

### CODE REVIEW

**Comment by sckott** [comment]
thanks!

- Can you include some examples in your doc strings for the major methods?
- Can you add at least a few trivial tests to the test suite for these?

**Comment by jlegind** [comment]
Hi Scott,

Great points - I'll add usage examples, as well as a few tests.

Best,
Jan

On Mon, May 30, 2016 at 6:10 PM, Scott Chamberlain <notifications@github.com

**Comment by peterdesmet** [comment]
Hi all,

@stijnvanhoey has meanwhile created a pull request to add more functionality to @jlegind download package (https://github.com/jlegind/GBIF-downloads/pull/1). Stijn and I discussed this morning how that could be tidied up, and be sent as a new pull request to `pygbif`. @jlegind, would you be available for a Skype call next Monday (June 6) to discuss how we can combine our efforts?

Cheers,

Peter

**Comment by sckott** [comment]
Thanks for the update - will hold off on this

**Comment by jlegind** [comment]
@peterdesmet Hi, I am available for skype today - I have no appointments after 10:30 
My skype address is jan.legind

**Comment by peterdesmet** [comment]
@jlegind great, I'll call you at 10u30.

**Comment by jlegind** [comment]
@peterdesmet BTW, a small test was added to https://github.com/jlegind/GBIF-downloads

**Comment by stijnvanhoey** [comment]
@jlegind I'm integrating the tests here: https://github.com/stijnvanhoey/pygbif/blob/downloads/test/test-occurrences-download_request.py

**Comment by sckott** [comment]
@jlegind @stijnvanhoey @peterdesmet I assume PR #27 replace this PR. correct?

**Comment by stijnvanhoey** [comment]
indeed, the functionality of this PR has been integrated in PR #27.  If @jlegind has no further remarks, I would close this PR.

**Pull request closed without merging**
