### PR TITLE
Use tox to run tests on multiple versions of python

### PR DESCRIPTION
**Pull request by xrotwang**
Running tests with tox [1] has some advantages:
- Running tests with multiple versions of python is simple.
- Proper package installation is tested as well. So for example
  the presence of README.rst when setup.py is run can only be
  guaranteed when this file is packaged with pygbif. tox will discover
  issues like this.

[1] https://pypi.python.org/pypi/tox

### CODE REVIEW

**Comment by sckott** [comment]
thanks, having a look

**Comment by sckott** [comment]
@xrotwang a few questions:

* how does integration with Travis happen? do we change this https://github.com/sckott/pygbif/blob/master/.travis.yml#L14-L15
* ever run into problems with `PYTHONPATH`? I often have this problem, where when I want to switch from python 2 to 3 and vice versa, I have to `unset PYTHONPATH`, then I can use python3, but after that python2 can't be found correctly - Any solutions?

**Comment by xrotwang** [comment]
No, Travis integration stays the same. `tox` does only help with running the tests locally. Basically, Travis and `tox` do the same thing: Create a `virtualenv` per python version, and run the tests there. But `tox` - unlike Travis - first creates a dist package from the sources and installs this dist package in each `virtualenv`. This is why I spotted the missing `MANIFEST.in`.

Since `tox` uses `virtualenv` to isolate test environements for each python version, problems with `PYTHONPATH` should not occur. This is taken care of by the `virtualenv` after all.

**Comment by sckott** [comment]
Hmm, i've always had a borked local python setup, so i'll just keep testing manually - and try to sort it out some day

**Pull request merged**
